#!/bin/bash

JOB_NAME=elasticsearch
RUN_DIR=/var/vcap/sys/run/$JOB_NAME
LOG_DIR=/var/vcap/sys/log/$JOB_NAME
CONFIG_DIR=/var/vcap/jobs/$JOB_NAME/config
EPHEMERAL=/var/vcap/data/$JOB_NAME
PERSISTENT=/var/vcap/store/$JOB_NAME
PIDFILE=$RUN_DIR/$JOB_NAME.pid
RUNAS=vcap

exec 1>> $LOG_DIR/$JOB_NAME.stdout.log
exec 2>> $LOG_DIR/$JOB_NAME.stderr.log

PATH=/var/vcap/packages/java/bin:$PATH
PATH=/var/vcap/packages/elasticsearch/bin:$PATH
JAVA_HOME=/var/vcap/packages/java

export PATH JAVA_HOME

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR $EPHEMERAL $PERSISTENT
    chown -R $RUNAS:$RUNAS $RUN_DIR $LOG_DIR $EPHEMERAL $PERSISTENT

    ## Start Code Here
    chpst -u $RUNAS:$RUNAS elasticsearch -p $PIDFILE \
      -Des.config=$CONFIG_DIR/elasticsearch.yml

    ;;

  stop)
    PID=$(head -1 $PIDFILE)
    kill $PID
    while [ -e /proc/$PID ]; do sleep 0.1; done
    rm -f $PIDFILE
    ;;

  *)
  echo "Usage: elasticsearch_ctl {start|stop}" ;;
esac
