---
name: elasticsearch
director_uuid: 

release:
  name: elasticsearch
  version: latest

compilation:
  workers: 2
  network: compile
  cloud_properties:
    ram: 2048
    disk: 8096
    cpu: 2

# this section describes how updates are handled
update:
  canaries: 1
  canary_watch_time: 30000
  update_watch_time: 30000
  max_in_flight: 1
  max_errors: 1

networks:

- name: compile
  subnets:
  - range: 10.244.0.240/30
    reserved: [ '10.244.0.241 - 10.244.0.241' ]
    cloud_properties:
      name: random
  - range: 10.244.0.244/30
    reserved: [ '10.244.0.245 - 10.244.0.245' ]
    cloud_properties:
      name: random

- name: default
  subnets:
  - range: 10.244.0.128/30
    reserved: [ '10.244.0.129 - 10.244.0.129' ]
    static:   [ '10.244.0.130 - 10.244.0.130' ]
    cloud_properties:
      name: random
  - range: 10.244.0.132/30
    reserved: [ '10.244.0.133 - 10.244.0.133' ]
    static:   [ '10.244.0.134 - 10.244.0.134' ]
    cloud_properties:
      name: random
  - range: 10.244.0.136/30
    reserved: [ '10.244.0.137 - 10.244.0.137' ]
    cloud_properties:
      name: random
  - range: 10.244.0.140/30
    reserved: [ '10.244.0.141 - 10.244.0.141' ]
    cloud_properties:
      name: random
  - range: 10.244.0.144/30
    reserved: [ '10.244.0.145 - 10.244.0.145' ]
    cloud_properties:
      name: random
  - range: 10.244.0.148/30
    reserved: [ '10.244.0.149 - 10.244.0.149' ]
    cloud_properties:
      name: random

resource_pools:

- name: infrastructure
  network: default
  size: 4
  stemcell:
    name: bosh-stemcell 
    version: latest
  cloud_properties:
    cpu: 1

jobs:

- name: elasticsearch
  template: elasticsearch
  persistent_disk: 2048
  instances: 2
  resource_pool: infrastructure 
  networks:
  - name: default
    static_ips: &ping_hosts
    - 10.244.0.130
    - 10.244.0.134

- name: elasticsearch-dynamic
  template: elasticsearch
  persistent_disk: 2048
  instances: 2
  resource_pool: infrastructure 
  networks:
  - name: default

properties:

  elasticsearch:
    cluster: my-awesome-cluster
    ping_hosts: *ping_hosts
